[package]
name = "smart-goal-kanban"
version = "0.1.0"
authors = ["dsbarnes"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.10.0"
termion = "1.5.5"
clap = "2.33.3"
rand = "0.7.3"
